/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIGambar;

import java.awt.CardLayout;

/**
 *
 * @author LENOVO
 */
public class AplikasiPenampilGambarGUI extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenampilGambarGUI
     */
    public AplikasiPenampilGambarGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLayout = new javax.swing.JPanel();
        gambarLbl1 = new javax.swing.JLabel();
        gambarLbl2 = new javax.swing.JLabel();
        gambarLbl3 = new javax.swing.JLabel();
        buttonLayout = new javax.swing.JPanel();
        pic1 = new javax.swing.JButton();
        pic2 = new javax.swing.JButton();
        pic3 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLayout.setLayout(new java.awt.CardLayout());

        gambarLbl1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Saved Pictures\\FT86.jpg")); // NOI18N
        gambarLbl1.setText("jLabel1");
        imageLayout.add(gambarLbl1, "0");

        gambarLbl2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Saved Pictures\\AMG Gts Coupe.jpg")); // NOI18N
        gambarLbl2.setText("jLabel2");
        imageLayout.add(gambarLbl2, "1");

        gambarLbl3.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Pictures\\Saved Pictures\\AMG GTR.jpg")); // NOI18N
        gambarLbl3.setText("jLabel3");
        imageLayout.add(gambarLbl3, "2");

        getContentPane().add(imageLayout, java.awt.BorderLayout.CENTER);

        pic1.setText("GT-86");
        pic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic1ActionPerformed(evt);
            }
        });
        buttonLayout.add(pic1);

        pic2.setText("AMG GT-S Coupe");
        pic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic2ActionPerformed(evt);
            }
        });
        buttonLayout.add(pic2);

        pic3.setText("AMG GT-R");
        pic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pic3ActionPerformed(evt);
            }
        });
        buttonLayout.add(pic3);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        buttonLayout.add(exitBtn);

        getContentPane().add(buttonLayout, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic1ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imageLayout.getLayout());
        cl.show (imageLayout,"0");
    }//GEN-LAST:event_pic1ActionPerformed

    private void pic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic2ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imageLayout.getLayout());
        cl.show (imageLayout,"1");
    }//GEN-LAST:event_pic2ActionPerformed

    private void pic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pic3ActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(imageLayout.getLayout());
        cl.show (imageLayout,"2");
    }//GEN-LAST:event_pic3ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonLayout;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel gambarLbl1;
    private javax.swing.JLabel gambarLbl2;
    private javax.swing.JLabel gambarLbl3;
    private javax.swing.JPanel imageLayout;
    private javax.swing.JButton pic1;
    private javax.swing.JButton pic2;
    private javax.swing.JButton pic3;
    // End of variables declaration//GEN-END:variables
}
